### ISSUE TITLE
'Contributor Covenant' link is broken

### ISSUE THREAD

**Issue by AJFaraday** [paulodiniz/minitest-volkswagen#4]
The 'Contributor Covenant' link at the bottom of README.md doesn't appear to be going anywhere. It appears that the way the link is formed appends it to the current url.

https://github.com/paulodiniz/minitest-volkswagen/blob/master/contributor-covenant.org

It might be as simple as starting this link with 'http://www.'

**Comment by paulodiniz** [comment]
Code of conduct updated. I'll send it to Volkswagen as well
